{{- if .Values.externalsecrets.enabled -}}
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ include "newApp.fullname" . }}
  labels:
    {{- include "newApp.labels" . | nindent 4 }}
spec:
  backendType: {{ .Values.externalsecrets.backendType | default "vault" }}
  vaultMountPoint:  {{ .Values.externalsecrets.vaultMountPoint }}
  vaultRole: {{ .Values.externalsecrets.vaultRole }}
  kvVersion: {{ .Values.externalsecrets.kvVersion }}
  dataFrom:
    - {{ .Values.externalsecrets.dataFrom }}
{{- end }}
