{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "newApp.fullname" . }}
  labels:
    {{- include "newApp.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "newApp.selectorLabels" . | nindent 6 }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
{{- end }}