{{- if .Values.vault.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "newApp.fullname" . }}-secret
  labels:
    {{- include "newApp.labels" . | nindent 4 }}
data:
  vault.properties: {{ .Values.vault.properties }}
{{- end }}
