{{- if .Values.services.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "newApp.fullname" . }}
  labels:
    {{- include "newApp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "newApp.selectorLabels" . | nindent 4 }}
{{- end }}
